package db

import "pec2/internal/models"

var Maquinas = []models.Maquina{
	{
		ID:          1,
		Nombre:      "Chest Press Biomecánico",
		Marca:       "Panatta Sport",
		Zona:        "Tren Superior",
		Descripcion: "Máquina diseñada para trabajar el pectoral de forma segura y biomecánicamente perfecta. Aisla el músculo y permite cargar peso sin comprometer los hombros.",
		Beneficios:  "Desarrollo máximo del pectoral mayor, deltoides anterior y tríceps. Ideal para hipertrofia segura.",
		Imagen:      "/img/maquinaria/ChestPress.webp",
	},
	{
		ID:          2,
		Nombre:      "Iso-Lateral Row",
		Marca:       "Hammer Strength",
		Zona:        "Tren Superior",
		Descripcion: "Permite trabajar la espalda de forma unilateral, corrigiendo asimetrías y logrando una contracción máxima de los dorsales y romboides.",
		Beneficios:  "Mejora la densidad de la espalda, corrige desequilibrios musculares y fortalece el core al requerir estabilización.",
		Imagen:      "/img/maquinaria/IsoLateralRow.webp",
	},
	{
		ID:          3,
		Nombre:      "Leg Press 45°",
		Marca:       "Cybex",
		Zona:        "Tren Inferior",
		Descripcion: "Prensa de piernas a 45 grados con rieles ultrasuaves. Permite mover grandes cargas con total seguridad para la columna lumbar.",
		Beneficios:  "Desarrollo masivo de cuádriceps, glúteos e isquiosurales sin tensión en la espalda baja.",
		Imagen:      "/img/maquinaria/LegPress.webp",
	},
	{
		ID:          4,
		Nombre:      "Hack Squat Lineal",
		Marca:       "Nautilus",
		Zona:        "Tren Inferior",
		Descripcion: "Simula el movimiento de una sentadilla pero proporcionando un apoyo total a la espalda. Ideal para enfocar el esfuerzo en los cuádriceps.",
		Beneficios:  "Hipertrofia extrema en las piernas, menos riesgo de lesión de rodilla gracias a la biomecánica guiada.",
		Imagen:      "/img/maquinaria/HackSquat.jpg",
	},
	{
		ID:          5,
		Nombre:      "Abdominal Crunch",
		Marca:       "Technogym",
		Zona:        "Core (Abdomen)",
		Descripcion: "Máquina de aislamiento para la pared abdominal. Su diseño permite una flexión del tronco perfecta aislando el recto abdominal.",
		Beneficios:  "Fortalecimiento del core, prevención de dolores lumbares y desarrollo estético del abdomen.",
		Imagen:      "/img/maquinaria/AbdominalCrunch.jpg",
	},
	{
		ID:          6,
		Nombre:      "Cable Crossover",
		Marca:       "Panatta Sport",
		Zona:        "Tren Superior",
		Descripcion: "Estación de poleas cruzadas de alta precisión con múltiples alturas ajustables. Perfecta para ejercicios de aislamiento.",
		Beneficios:  "Trabajo constante durante todo el rango de movimiento, ideal para bombear sangre al final del entrenamiento.",
		Imagen:      "/img/maquinaria/CableCrossover.png",
	},
	{
		ID:          7,
		Nombre:      "Lat Pulldown Convergente",
		Marca:       "Hammer Strength",
		Zona:        "Tren Superior",
		Descripcion: "Máquina para jalón al pecho con movimiento convergente, lo que permite un estiramiento y contracción superior a los jalones tradicionales.",
		Beneficios:  "Ensanchamiento de la espalda (dorsal ancho) y mejora de la fuerza de tracción.",
		Imagen:      "/img/maquinaria/LatPulldown.avif",
	},
	{
		ID:          8,
		Nombre:      "Glute Drive",
		Marca:       "Nautilus",
		Zona:        "Tren Inferior",
		Descripcion: "Máquina diseñada específicamente para el Hip Thrust. Elimina la necesidad de usar barra libre e incomodidad en la pelvis.",
		Beneficios:  "Desarrollo óptimo de los glúteos, mejora el rendimiento atlético sin sobrecargar la espalda.",
		Imagen:      "/img/maquinaria/GluteDrive.webp",
	},
}

var Servicios = []models.Servicio{
	{
		ID:               1,
		Nombre:           "Sala de Máquinas",
		Icono:            "fas fa-dumbbell",
		DescripcionBreve: "Bio-mechanics focus. Equipamiento seleccionado científicamente para aislar cada grupo muscular de forma estricta.",
		DescripcionLarga: "Nuestra sala de musculación cuenta con más de 100 máquinas de marcas premium (Panatta, Hammer Strength, Cybex). Cada zona está optimizada para diferentes grupos musculares, con luz controlada y ambiente enfocado al rendimiento puro. Perfecto tanto para principiantes como para culturistas de élite.",
		Beneficios:       "Equipamiento de máxima calidad, cero tiempos de espera gracias a duplicados de máquinas populares y entorno motivador.",
	},
	{
		ID:               2,
		Nombre:           "Fisioterapia Premium",
		Icono:            "fas fa-user-md",
		DescripcionBreve: "Recuperación profunda, punción seca, liberación miofascial y osteopatía al servicio de tu rendimiento.",
		DescripcionLarga: "Un equipo de fisioterapeutas deportivos a tu disposición. Tratamos lesiones agudas, crónicas y realizamos labores de prevención. Utilizamos técnicas avanzadas de terapia manual, electrolisis percutánea, neuromodulación y trabajo activo.",
		Beneficios:       "Recuperación acelerada, prevención de lesiones y tratamientos personalizados.",
	},
	{
		ID:               3,
		Nombre:           "Nutricionista",
		Icono:            "fas fa-apple-alt",
		DescripcionBreve: "Planes dietéticos personalizados, periodización nutricional y análisis corporal por pliegues y DEXA.",
		DescripcionLarga: "Alcanza tus objetivos más rápido con nuestro servicio de nutrición clínica y deportiva. Incluye valoración antropométrica detallada, diseño de planes de alimentación adaptables y seguimiento continuo para garantizar que tu dieta apoye tu entrenamiento.",
		Beneficios:       "Pérdida de grasa eficiente, aumento de masa muscular limpio y mejora del rendimiento.",
	},
	{
		ID:               4,
		Nombre:           "Sauna Finlandesa",
		Icono:            "fas fa-hot-tub",
		DescripcionBreve: "Relajación térmica para eliminación de toxinas, mejora cardiovascular y recuperación del sistema nervioso.",
		DescripcionLarga: "Termina tu sesión de entrenamiento pesado relajándote en nuestras saunas finlandesas de madera de pino a 85°C. Un entorno perfecto para la recuperación muscular y el bienestar mental.",
		Beneficios:       "Mejora del flujo sanguíneo, relajación muscular profunda y beneficios cardiovasculares.",
	},
	{
		ID:               5,
		Nombre:           "Piscina Olímpica",
		Icono:            "fas fa-swimmer",
		DescripcionBreve: "50 metros de longitud, temperatura controlada y uso reservado por carriles para entreno de impacto cero.",
		DescripcionLarga: "Piscina de 50 metros con 8 calles disponibles para nado libre o entrenamientos dirigidos. El agua está tratada con sal, evitando los químicos agresivos del cloro tradicional, lo que beneficia a tu piel y respiración.",
		Beneficios:       "Cardio sin impacto articular, mejora de la capacidad pulmonar y recuperación activa.",
	},
	{
		ID:               6,
		Nombre:           "Crioterapia",
		Icono:            "fas fa-snowflake",
		DescripcionBreve: "Terapias bajo cero (-110°C) para acelerar recuperación muscular y reducir niveles de inflamación.",
		DescripcionLarga: "Las cabinas de crioterapia de cuerpo entero someten a tu cuerpo a temperaturas extremas por corto tiempo (2-3 minutos). Este shock térmico desencadena potentes respuestas antiinflamatorias y analgésicas en todo el cuerpo.",
		Beneficios:       "Reducción del estrés oxidativo, disminución drástica del dolor post-entrenamiento e incremento de energía.",
	},
}
